import type { SlideInput } from "./schema.js"
import { validateSlides } from "./schema.js"

const DECK = { width: 13.333, height: 7.5, margin: 0.8, titleY: 0.6, contentY: 1.7 } as const
const FONT = "Microsoft YaHei"
type TextOptions = {
  x: number
  y: number
  w: number
  h: number
  fontSize: number
  align?: "left" | "center"
  bold?: boolean
  color?: string
  bullet?: { indent: number }
  margin?: number
  breakLine?: boolean
  valign?: "mid"
  fontFace?: string
}
type Slide = {
  background: { color: string }
  addText(text: string, options: TextOptions): Slide
  addNotes(notes: string): Slide
}
type Presentation = {
  layout: string
  title: string
  author: string
  subject: string
  addSlide(): Slide
  writeFile(input: { fileName: string; compression: boolean }): Promise<string>
}
type PptxConstructor = new () => Presentation

/** Creates a deterministic wide PPTX from explicit structured slides. */
export async function writePresentation(filePath: string, input: { title: string; slides: readonly SlideInput[] }) {
  validateSlides(input.slides)
  const module = await import("pptxgenjs")
  const Constructor = module.default as unknown as PptxConstructor
  const presentation = new Constructor()
  presentation.layout = "LAYOUT_WIDE"
  presentation.title = input.title
  presentation.author = "NeCode"
  presentation.subject = "Generated by NeCode Presentations plugin"
  input.slides.forEach((slide) => renderSlide(presentation, slide))
  await presentation.writeFile({ fileName: filePath, compression: true })
}

function renderSlide(presentation: Presentation, input: SlideInput) {
  const slide = presentation.addSlide()
  slide.background = { color: "F8FAFC" }
  const layout = input.layout ?? "title-and-content"
  if (layout === "title") renderTitleSlide(slide, input)
  if (layout === "title-and-content") renderContentSlide(slide, input)
  if (layout === "section") renderSectionSlide(slide, input)
  if (input.notes?.trim()) slide.addNotes(input.notes.trim())
}

function renderTitleSlide(slide: Slide, input: SlideInput) {
  slide.addText(
    input.title,
    textOptions({
      x: DECK.margin,
      y: 2.2,
      w: DECK.width - DECK.margin * 2,
      h: 1,
      fontSize: 30,
      align: "center",
      bold: true,
    }),
  )
  if (input.subtitle?.trim()) {
    slide.addText(
      input.subtitle.trim(),
      textOptions({
        x: DECK.margin,
        y: 3.35,
        w: DECK.width - DECK.margin * 2,
        h: 0.6,
        fontSize: 18,
        align: "center",
        color: "475569",
      }),
    )
  }
}

function renderSectionSlide(slide: Slide, input: SlideInput) {
  slide.addText(
    input.title,
    textOptions({ x: DECK.margin, y: 2.45, w: DECK.width - DECK.margin * 2, h: 0.9, fontSize: 28, bold: true }),
  )
  if (input.subtitle?.trim()) {
    slide.addText(
      input.subtitle.trim(),
      textOptions({ x: DECK.margin, y: 3.45, w: DECK.width - DECK.margin * 2, h: 0.6, fontSize: 17, color: "475569" }),
    )
  }
}

function renderContentSlide(slide: Slide, input: SlideInput) {
  slide.addText(
    input.title,
    textOptions({ x: DECK.margin, y: DECK.titleY, w: DECK.width - DECK.margin * 2, h: 0.65, fontSize: 24, bold: true }),
  )
  if (input.subtitle?.trim()) {
    slide.addText(
      input.subtitle.trim(),
      textOptions({ x: DECK.margin, y: 1.25, w: DECK.width - DECK.margin * 2, h: 0.4, fontSize: 14, color: "64748B" }),
    )
  }
  input.bullets?.forEach((bullet, index) => {
    slide.addText(
      bullet,
      textOptions({ x: 1.1, y: DECK.contentY + index * 0.65, w: 11.2, h: 0.45, fontSize: 19, bullet: { indent: 18 } }),
    )
  })
}

function textOptions(input: TextOptions) {
  return { margin: 0, breakLine: false, valign: "mid" as const, color: "0F172A", fontFace: FONT, ...input }
}
